[package]

name = "rlisp"
version = "0.0.1"
authors = ["Jonathan Nilsson <lord.jonil@gmail.com>"]

[dependencies.mpc]
path = "../mpc"

[dependencies.phf]
git = "https://github.com/JoNil/rust-phf.git"

[dependencies.phf_mac]
git = "https://github.com/JoNil/rust-phf.git"